version: "3"
services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: postgres.transpong.42.com
    ports:
      - 5432:5432
    networks:
      - transpong

  server:
    build:
      context: ./server
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 3001:3001
    networks:
      - transpong

  client:
    build:
      context: ./client
    depends_on:
      - server
    env_file:
      - .env
    ports:
      - 5173:5173
    networks:
      - transpong

networks:
  transpong:
    driver: bridge
