version: "3"
services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: postgres.transpong.42.com
    ports:
      - 5432:5432